spring:
  datasource:
    default:
      jdbc-url: jdbc:sqlite:C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/main.db
      driver-class-name: org.sqlite.JDBC
    shp:
      jdbc-url: jdbc:postgresql://localhost:5432/shp_dataset?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: QWERBOOM123
    ship:
      jdbc-url: jdbc:sqlite:C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/resources/ais.db
      driver-class-name: org.sqlite.JDBC
    waterway:
      jdbc-url: jdbc:sqlite:C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/resources/waterway.db
      driver-class-name: org.sqlite.JDBC

#C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/

baseDir: C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/resources/raw/
avatarDir: C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/resources/avatar/
tempDir: C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/temp/
visualDir: C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/resources/visual/
pgPath: D:/App/postgresql/bin/
mapDir: C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/resources/map/
resourceDir: C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/resources/
analysisDir: C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/resources/analysis/
analysisParameterDir: C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/resources/analysisParameter/
projectDir: C:/UyNauhL/Working/Assignments/MONITOR/data/monitor/monitor/resources/raw/project/

meteorologyUrl: https://weather.cma.cn/api/map/alarm
meteorologyPngUrl:
  http://data.cma.cn/dataGis/static/ultra/img/gis/disasterWarning/

waterLevelAddress:
  https://geomodeling.njnu.edu.cn/waterLevel

AISUrl:
  https://www.cjienc.cn/rest/es/getBoxShips?left={0}&bottom={1}&right={2}&top={3}
AISListUrl:
  https://www.cjienc.cn/rest/es/getBoxShips?from={0}&name={1}&size={2}

