spring:
  datasource:
    default:
      jdbc-url: jdbc:sqlite:D:/desktop/桌面/Assignments/data/monitor/monitor/main.db
      driver-class-name: org.sqlite.JDBC
    shp:
      jdbc-url: jdbc:postgresql://localhost:5432/shp_dataset?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: QWERBOOM123
    ship:
      jdbc-url: jdbc:sqlite:D:/desktop/桌面/Assignments/data/monitor/monitor/resources/ais.db
      driver-class-name: org.sqlite.JDBC
    waterway:
      jdbc-url: jdbc:sqlite:D:/desktop/桌面/Assignments/data/monitor/monitor/resources/waterway.db
      driver-class-name: org.sqlite.JDBC



baseDir: D:/desktop/桌面/Assignments/data/monitor/monitor/
avatarDir: D:/desktop/桌面/Assignments/data/monitor/monitor/resources/avatar
tempDir: D:/desktop/桌面/Assignments/data/monitor/monitor/temp
visualDir: D:/desktop/桌面/Assignments/data/monitor/monitor/resources/visual/
pgPath: D:/Program Files (x86)/postgresql/15/bin
mapDir: D:/desktop/桌面/Assignments/data/monitor/monitor/resources/map/
resourceDir: D:/desktop/桌面/Assignments/data/monitor/monitor/resources/

meteorologyUrl: https://weather.cma.cn/api/map/alarm
meteorologyPngUrl:
  http://data.cma.cn/dataGis/static/ultra/img/gis/disasterWarning/

waterLevelAddress:
  https://geomodeling.njnu.edu.cn/waterLevel

AISUrl:
  https://www.cjienc.cn/rest/es/getBoxShips?left={0}&bottom={1}&right={2}&top={3}
AISListUrl:
  https://www.cjienc.cn/rest/es/getBoxShips?from={0}&name={1}&size={2}

