spring:
  datasource:
    default:
      jdbc-url: jdbc:sqlite:D:/UyNauhL/Assignments/monitor_data/monitor/main.db
      driver-class-name: org.sqlite.JDBC
    shp:
      jdbc-url: jdbc:postgresql://localhost:5432/shp_dataset?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123
    ship:
      jdbc-url: jdbc:sqlite:D:/UyNauhL/Assignments/monitor_data/monitor/resources/ais.db
      driver-class-name: org.sqlite.JDBC
    waterway:
      jdbc-url: jdbc:sqlite:D:/UyNauhL/Assignments/monitor_data/monitor/resources/waterway.db
      driver-class-name: org.sqlite.JDBC

#D:/UyNauhL/Assignments/monitor_data/monitor

baseDir: D:/UyNauhL/Assignments/monitor_data/monitor/resources/raw/
avatarDir: D:/UyNauhL/Assignments/monitor_data/monitor/resources/avatar/
tempDir: D:/UyNauhL/Assignments/monitor_data/monitor/temp/
visualDir: D:/UyNauhL/Assignments/monitor_data/monitor/resources/visual/
pgPath: C:/UyNauhL/ProgramFile/PostgreSQL/11/bin/
mapDir: D:/UyNauhL/Assignments/monitor_data/monitor/resources/map/
resourceDir: D:/UyNauhL/Assignments/monitor_data/monitor/resources/
analysisDir: D:/UyNauhL/Assignments/monitor_data/monitor/resources/analysis/
analysisParameterDir: D:/UyNauhL/Assignments/monitor_data/monitor/resources/analysisParameter/
projectDir: D:/UyNauhL/Assignments/monitor_data/monitor/project/

meteorologyUrl: https://weather.cma.cn/api/map/alarm
meteorologyPngUrl:
  http://data.cma.cn/dataGis/static/ultra/img/gis/disasterWarning/

waterLevelAddress:
  https://geomodeling.njnu.edu.cn/waterLevel

AISUrl:
  https://www.cjienc.cn/rest/es/getBoxShips?left={0}&bottom={1}&right={2}&top={3}
AISListUrl:
  https://www.cjienc.cn/rest/es/getBoxShips?from={0}&name={1}&size={2}

fileViewUrl:
  http://localhost:8012/fileUpload