server:
  port: 8700
spring:
  profiles:
    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 25MB



mybatis:
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
    call-setters-on-nulls: true