spring:
  datasource:
    default:
      jdbc-url: jdbc:sqlite:E:/monitor/main.db
      driver-class-name: org.sqlite.JDBC
    shp:
      jdbc-url: jdbc:postgresql://localhost:5432/shp_dataset?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123
    ship:
      jdbc-url: jdbc:sqlite:E:/monitor/resource/ais.db
      driver-class-name: org.sqlite.JDBC
    waterway:
      jdbc-url: jdbc:sqlite:E:/monitor/resource/waterway.db
      driver-class-name: org.sqlite.JDBC



baseDir: E:/monitor/resources/raw/
avatarDir: E:/monitor/resources/avatar/
tempDir: E:/monitor/temp/
visualDir: E:/monitor/resources/visual/
pgPath: D:/App/postgresql/bin/
mapDir: E:/monitor/resources/map/

